name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm" # Menggunakan cache npm

      - name: Install Dependencies
        run: npm ci # Menggunakan "npm ci" untuk instalasi dependencies

      - name: Build Next.js App
        run: npm run build
