name: Build NextJS
on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.yarnpkg.com"

      - name: Install Dependencies
        run: yarn install

      - name: Build Next.js App
        run: yarn build
